FROM golang:1.26-alpine

WORKDIR /app
COPY contracts/auth-service contracts/auth-service
COPY web-backend/auth-service/go.mod web-backend/auth-service/go.sum ./

RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY web-backend/auth-service/ .

EXPOSE 8080

CMD ["air"]