server {
    listen 80;
    resolver 127.0.0.11 valid=10s;

    location /api/auth/ {
        set $upstream "http://localhost:8080";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarder_for;
        proxy_pass $upstream;
    }

    location /api/course/ {
        set $upstream "http://auth-service:8082"
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarder_for;
        proxy_pass $upstream;
    }

    location /api/payment/ {
        set $upstream "http://payment-service:8083"
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarder_for;
        proxy_pass $upstream;
    }
}